"""
DRAW_FB_MONO v 0.1.4
Draw library for monochrome displays

Color: 1-bit monochrome
 
Project path: https://github.com/r2d2-arduino/tft_draw
MIT License

Author: Arthur Derkach 
"""
from framebuf import FrameBuffer, MONO_VLSB, MONO_HMSB, MONO_HLSB
from micropython import const

class DRAW_FB_MONO (FrameBuffer):
    
    BITS_PER_PIXEL = const( 1 )
    
    def __init__( self, width, height, rotation = 0, fb_type = 0 ):
        
        self.width  = width
        self.height = height
        self.rotation = rotation
        
        self.buffsize = width * height // 8
        self.buffer = bytearray( self.buffsize )
        
        self.font = None
        self.text_wrap = False
        
        if fb_type == 1:
            fb_format = MONO_HLSB
            
            if self.rotation & 1:
                fb_format = MONO_HMSB
                
        else: # fb_type == 0:
            fb_format = MONO_VLSB
            if self.rotation & 1:
                fb_format = MONO_HMSB                    

        super().__init__( self.buffer, self.width, self.height, fb_format )
        
    def swap_dimensions(self):
        """ Swaps width and height for 90/270 degree rotation. """
        self.width, self.height = self.height, self.width
        
    # *** TEXT AREA ***

    def set_font( self, font ):
        """ Set font for text
        Args
        font (module): Font module generated by font_to_py.py
        """
        self.font = font
        
    def set_text_wrap( self, on = True ):
        """ Set text wrapping """
        self.text_wrap = bool( on )        

    def draw_text( self, text, x, y, color = 1 ):
        """ Draw text on display
        Args
        x (int) : Start X position
        y (int) : Start Y position
        """
        x_start = x
        screen_height = self.height
        screen_width  = self.width

        font = self.font
        wrap = self.text_wrap

        if font == None:
            print("Font not set")
            return False
        
        bitmap = self.draw_bitmap
        getch = font.get_ch
        
        for char in text:   
            glyph = getch(char)
            glyph_height = glyph[1]
            glyph_width  = glyph[2]
            
            if char == " ": # double size for space
                x += glyph_width            

            if wrap and (x + glyph_width > screen_width): # End of row
                x = x_start
                y += glyph_height

            #if y + glyph_height > screen_height: # End of screen
            #    break
            
            #fb = FrameBuffer(bytearray(glyph[0]), glyph_width, glyph_height, MONO_HLSB)
            #self.blit(fb, x, y, 1 - color)
            
            bitmap(glyph, x, y, color)
            x += glyph_width
        return (x, y)

    @micropython.viper
    def draw_bitmap( self, bitmap, x:int, y:int, color:int ):
        """ Draw a bitmap on display
        Args
        bitmap (bytes): Bitmap data
        x      (int): Start X position
        y      (int): Start Y position
        color  (int): Color 0 or 1
        """
        data   = ptr8( bitmap[0] ) #memoryview to bitmap
        height =  int( bitmap[1] )
        width  =  int( bitmap[2] )
        
        set_pixel = self.pixel
        
        i = 0
        for h in range( height ):
            bit_index = 0
            while bit_index < width:
                byte = data[i]
                
                if byte == 0: # empty byte
                    bit_index += 8
                    i += 1
                    continue
                
                xpos = bit_index + x
                ypos = h + y                
                #Drawing pixels when bit = 1
                for b in range(8):
                    if (byte >> b) & 1:
                        set_pixel( xpos + (7 - b), ypos, color )

                bit_index += 8
                i += 1        

    # *** IMAGE AREA ***

    def load_bmp( self, filename, x = 0, y = 0, color = 1 ):
        """ Load monochromatic BMP image on buffer
        Args
        filename (string): filename of image, example: "rain.bmp"
        x (int) : Start X position
        y (int) : Start Y position
        color  (int): Color 0 or 1
        """
        f = open(filename, 'rb')

        if f.read(2) == b'BM':  #header
            dummy    = f.read(8)
            offset   = int.from_bytes(f.read(4), 'little')
            dummy    = f.read(4) #hdrsize
            width    = int.from_bytes(f.read(4), 'little')
            height   = int.from_bytes(f.read(4), 'little')
            planes   = int.from_bytes(f.read(2), 'little')
            depth    = int.from_bytes(f.read(2), 'little')
            compress = int.from_bytes(f.read(4), 'little')

            if planes == 1 and depth == 1 and compress == 0: #compress method == uncompressed
                f.seek(offset)
                
                self._send_bmp_to_buffer( f, x, y, width, height, color)
            else:
                print("Unsupported planes, depth, compress:", planes, depth, compress )
                
        f.close()
        
    @micropython.viper
    def _send_bmp_to_buffer(self, f, x:int, y:int, width:int, height:int, color:int):
        """ Send bmp-file to buffer
        Args
        f (object File) : Image file
        x (int) : Start X position
        y (int) : Start Y position        
        width (int): Width of image frame
        height (int): Height of image frame
        color  (int): Color 0 or 1
        """         
        block_size = ((width + 31) // 32) * 4  # row file size
        row_bytes = (width + 7) // 8           # bytes in row
        
        bitmap = bytearray(row_bytes * height)
        bitmap_ptr = ptr8(bitmap)
        
        image_data = f.read(height * block_size)
        image_ptr = ptr8(image_data)
        
        for row in range(height):
            # Y inversion, for bmp have up side down order 
            src_row = (height - 1 - row)
            dest_offset = row * row_bytes
            src_offset = src_row * block_size
            
            for b in range(row_bytes):
                val = image_ptr[src_offset + b]
                # Color inversion, if set
                if color == 1:
                    val ^= 0xFF
                bitmap_ptr[dest_offset + b] = val

        # Creation of temp FB and copy to main FB
        fb = FrameBuffer(bitmap, width, height, MONO_HLSB)
        self.blit(fb, x, y)    


