"""
DRAW_FB_G8 v 0.1.2
Draw library for monochrome displays

Color: 1-byte color
 
Project path: https://github.com/r2d2-arduino/tft_draw
MIT License

Author: Arthur Derkach 
"""
from framebuf import FrameBuffer, GS8, MONO_HLSB

class DRAW_FB_G8 (FrameBuffer):
    
    def __init__( self, width, height, rotation = 0 ):
        
        self.width  = width
        self.height = height
        self.rotation = rotation
        
        self.buffsize = width * height
        self.buffer = bytearray( self.buffsize )
        
        self.font = None
        self.text_wrap = False                   

        super().__init__( self.buffer, self.width, self.height, GS8 )
        
    def swap_dimensions(self):
        """ Swaps width and height for 90/270 degree rotation. """
        self.width, self.height = self.height, self.width
        
    # *** TEXT AREA ***

    def set_font( self, font ):
        """ Set font for text
        Args
        font (module): Font module generated by font_to_py.py
        """
        self.font = font
        
    def set_text_wrap( self, on = True ):
        """ Set text wrapping """
        self.text_wrap = bool( on )        

    def draw_text( self, text, x, y, color = 1 ):
        """ Draw text on display
        Args
        x (int) : Start X position
        y (int) : Start Y position
        """
        x_start = x
        screen_height = self.height
        screen_width  = self.width

        font = self.font
        wrap = self.text_wrap

        if font == None:
            print("Font not set")
            return False
        
        bitmap = self.draw_bitmap
        getch = font.get_ch
        
        for char in text:   
            glyph = getch(char)
            glyph_height = glyph[1]
            glyph_width  = glyph[2]
            
            if char == " ": # double size for space
                x += glyph_width            

            #if wrap and (x + glyph_width > screen_width): # End of row
            #    x = x_start
            #    y += glyph_height

            #if y + glyph_height > screen_height: # End of screen
            #    break
            
            bitmap(glyph, x, y, color)
            x += glyph_width
        return (x, y)

    @micropython.viper
    def draw_bitmap( self, bitmap, x:int, y:int, color:int ):
        """ Draw a bitmap on display
        Args
        bitmap (bytes): Bitmap data
        x      (int): Start X position
        y      (int): Start Y position
        color  (int): Color 0 or 1
        """
        data   = ptr8( bitmap[0] ) #memoryview to bitmap
        height =  int( bitmap[1] )
        width  =  int( bitmap[2] )
        screen_width = int(self.width)
        
        buf = ptr8(self.buffer)
        #set_pixel = self.pixel
        
        i = 0
        for h in range( height ):
            bit_index = 0
            while bit_index < width:
                byte = data[i]
                
                if byte == 0: # empty byte
                    bit_index += 8
                    i += 1
                    continue
                
                xpos = bit_index + x
                ypos = h + y                
                #Drawing pixels when bit = 1
                for b in range(8):
                    if (byte >> b) & 1:
                        #set_pixel( xpos + (7 - b), ypos, color )
                        buf[ xpos + (7 - b) + (ypos * screen_width) ] = color

                bit_index += 8
                i += 1        

    # *** IMAGE AREA ***
            
    def load_mono( self, filename, x = 0, y = 0, color = 1 ):
        """ Load monochromatic BMP image on buffer
        Args
        filename (string): filename of image, example: "rain.bmp"
        x (int) : Start X position
        y (int) : Start Y position
        color  (int): Color 0 or 1
        """
        with open(filename, 'rb') as f:
            if f.read(2) == b'BM':  #header
                dummy    = f.read(8)
                offset   = int.from_bytes(f.read(4), 'little')
                dummy    = f.read(4) #hdrsize
                width    = int.from_bytes(f.read(4), 'little')
                height   = int.from_bytes(f.read(4), 'little')
                planes   = int.from_bytes(f.read(2), 'little')
                depth    = int.from_bytes(f.read(2), 'little')
                compress = int.from_bytes(f.read(4), 'little')

                if planes == 1 and depth == 1 and compress == 0: #compress method == uncompressed
                    f.seek(offset)
                    
                    self._send_mono_to_buffer( f, x, y, width, height, color)
                else:
                    print("Unsupported planes, depth, compress:", planes, depth, compress )
                    
        
    @micropython.viper
    def _send_mono_to_buffer(self, f, x:int, y:int, width:int, height:int, color:int):
        """ Send bmp-file to buffer
        Args
        f (object File) : Image file
        x (int) : Start X position
        y (int) : Start Y position        
        width (int): Width of image frame
        height (int): Height of image frame
        color  (int): Color 0 or 1
        """         
        block_size = ((width + 31) // 32) * 4  # row file size
        row_bytes = (width + 7) // 8           # bytes in row
        
        bitmap = bytearray(row_bytes * height)
        bitmap_ptr = ptr8(bitmap)
        
        image_data = f.read(height * block_size)
        image_ptr = ptr8(image_data)
        
        for row in range(height):
            # Y inversion, for bmp have up side down order 
            src_row = (height - 1 - row)
            dest_offset = row * row_bytes
            src_offset = src_row * block_size
            
            for b in range(row_bytes):
                #val = image_ptr[src_offset + b]
                bitmap_ptr[dest_offset + b] = image_ptr[src_offset + b] ^0xFF
        
        # Creation of temp FB and copy to main FB
        self.draw_bitmap( (bitmap, height, width), x, y, color )
        #fb = FrameBuffer(bitmap, width, height, MONO_HLSB)
        #self.blit(fb, x, y)

    def load_bmp( self, filename, x = 0, y = 0 ):
        """ Load monochromatic BMP image on buffer
        Args
        filename (string): filename of image, example: "rain.bmp"
        x (int) : Start X position
        y (int) : Start Y position
        """
        with open(filename, 'rb') as f:
            if f.read(2) != b'BM':  #header
                raise ValueError("It is not BMP file")
            
            f.seek(10)
            pixel_data_offset = int.from_bytes(f.read(4), 'little')
            
            f.seek(14)
            dib_header_size = int.from_bytes(f.read(4), 'little')
            
            width  = int.from_bytes(f.read(4), 'little')
            height = int.from_bytes(f.read(4), 'little', True)
            
            f.seek(28)
            bpp = int.from_bytes(f.read(2), 'little')
            if bpp != 8:
                raise ValueError("8-bit BMP support only")
        
            # Reading palette (256 colors, 4 bytes each: Blue, Green, Red, Reserved)
            f.seek(14 + dib_header_size)
            palette_data = f.read(256 * 4)
            
            f.seek(pixel_data_offset)
            
            self._send_bmp_to_buffer( f, palette_data, x, y, width, height )

    @micropython.viper
    def _send_bmp_to_buffer(self, f, palette_data, offset_x:int, offset_y:int, width:int, height:int ):
        """
        Loads an 8-bit BMP file into the framebuffer
        f (file): File object
        palette_data (bytearray): 256 colors palette
        offset_x: X offset
        offset_y: Y offset
        width (int): Image width
        height (int) Image height
        
        """
        lut = bytearray(256)
        for i in range(256):
            b = int(palette_data[i * 4])
            g = int(palette_data[i * 4 + 1])
            r = int(palette_data[i * 4 + 2])
            
            # Approximate conversion: 255 -> 7
            r_bit = 1 if r >= 128 else 0
            g_bit = 1 if g >= 128 else 0
            b_bit = 1 if b >= 128 else 0               

            # Collect color using a mask
            lut[i] = (r_bit << 2) | (g_bit << 1) | b_bit
        
        row_bytes = (width + 3) & ~3
        
        screen_width = int(self.width)
        screen_height = int(self.height)

        image_size = row_bytes * height
        image_data = f.read(image_size)
        
        buff = ptr8(self.buffer)
        buff_lut = ptr8(lut)
        buff_image = ptr8(image_data)
           
        for y in range(height):
            draw_y = height - 1 - y + offset_y
            
            if draw_y >= 0 and draw_y < screen_height:
                row_start_index = y * row_bytes
                
                for x in range(width):
                    draw_x = x + offset_x
                    
                    if draw_x >= 0 and draw_x < screen_width:

                        buff_pos = draw_y * screen_width + draw_x
                        img_pos = row_start_index + x
                        
                        buff[buff_pos] = buff_lut[buff_image[img_pos]]
                        