"""
DRAW_FB_G4 v 0.1.2
Draw library for monochrome displays

Color: 1-byte color
 
Project path: https://github.com/r2d2-arduino/tft_draw
MIT License

Author: Arthur Derkach 
"""
from framebuf import FrameBuffer, GS4_HMSB, MONO_HLSB, MONO_VLSB, MONO_HMSB

class DRAW_FB_G4 (FrameBuffer):
    
    def __init__( self, width, height, rotation = 0 ):
        
        self.width  = width
        self.height = height
        self.rotation = rotation
        
        self.buffsize = width * height // 2
        self.buffer = bytearray( self.buffsize )
        
        self.font = None
        self.text_wrap = False

        super().__init__( self.buffer, self.width, self.height, GS4_HMSB )
        
    def swap_dimensions(self):
        """ Swaps width and height for 90/270 degree rotation. """
        self.width, self.height = self.height, self.width
        
    # *** TEXT AREA ***

    def set_font( self, font ):
        """ Set font for text
        Args
        font (module): Font module generated by font_to_py.py
        """
        self.font = font
        
    def set_text_wrap( self, on = True ):
        """ Set text wrapping """
        self.text_wrap = bool( on )        

    def draw_text(self, text, x, y, color = 1):
        """ Draw text on display
        Args
        x (int) : Start X position
        y (int) : Start Y position
        """
        x_start = x
        screen_height = self.height
        screen_width  = self.width

        font = self.font

        if font == None:
            print("Font not set")
            return False

        getch = font.get_ch
        
        for char in text:   
            glyph = getch(char)
            glyph_height = glyph[1]
            glyph_width  = glyph[2]

            if char == " ": # double size for space
                x += glyph_width

            if x + glyph_width > screen_width: # End of row
                x = x_start
                y += glyph_height

            #if y + glyph_height > screen_height: # End of screen
            #    break
            
            self.draw_bitmap( glyph, x, y, color )

            x += glyph_width

    @micropython.viper
    def draw_bitmap(self, bitmap, x:int, y:int, color:int):
        """ Draw a bitmap on display
        Args
        bitmap (bytes): Bitmap data
        x      (int): Start X position
        y      (int): Start Y position
        color  (int): Color 0 or 1
        """
        data   = ptr8(bitmap[0]) #memoryview to bitmap
        height = int(bitmap[1])
        width  = int(bitmap[2])
        
        pixel = self.pixel
        
        i = 0
        for h in range(height):
            bit_index = 0
            while bit_index < width:
                byte = data[i]
                
                if byte == 0: # empty byte
                    bit_index += 8
                    i += 1
                    continue
                
                xpos = bit_index + x
                ypos = h + y

                #Drawing pixels when bit = 1
                if (byte >> 7) & 1:
                    pixel(xpos    , ypos, color)
                if (byte >> 6) & 1:
                    pixel(xpos + 1, ypos, color)
                if (byte >> 5) & 1:
                    pixel(xpos + 2, ypos, color)
                if (byte >> 4) & 1:
                    pixel(xpos + 3, ypos, color)
                if (byte >> 3) & 1:
                    pixel(xpos + 4, ypos, color)
                if (byte >> 2) & 1:
                    pixel(xpos + 5, ypos, color)
                if (byte >> 1) & 1:
                    pixel(xpos + 6, ypos, color)
                if byte & 1:
                    pixel(xpos + 7, ypos, color)

                bit_index += 8
                i += 1       

    # *** IMAGE AREA ***
            
    def load_mono( self, filename, x = 0, y = 0, color = 1 ):
        """ Load monochromatic BMP image on buffer
        Args
        filename (string): filename of image, example: "rain.bmp"
        x (int) : Start X position
        y (int) : Start Y position
        color  (int): Color 0 or 1
        """
        with open(filename, 'rb') as f:
            if f.read(2) == b'BM':  #header
                dummy    = f.read(8)
                offset   = int.from_bytes(f.read(4), 'little')
                dummy    = f.read(4) #hdrsize
                width    = int.from_bytes(f.read(4), 'little')
                height   = int.from_bytes(f.read(4), 'little')
                planes   = int.from_bytes(f.read(2), 'little')
                depth    = int.from_bytes(f.read(2), 'little')
                compress = int.from_bytes(f.read(4), 'little')

                if planes == 1 and depth == 1 and compress == 0: #compress method == uncompressed
                    f.seek(offset)
                    
                    self._send_mono_to_buffer( f, x, y, width, height, color)
                else:
                    print("Unsupported planes, depth, compress:", planes, depth, compress )
                    
        
    @micropython.viper
    def _send_mono_to_buffer(self, f, x:int, y:int, width:int, height:int, color:int):
        """ Send bmp-file to buffer
        Args
        f (object File) : Image file
        x (int) : Start X position
        y (int) : Start Y position        
        width (int): Width of image frame
        height (int): Height of image frame
        color  (int): Color 0 or 1
        """         
        block_size = ((width + 31) // 32) * 4  # row file size
        row_bytes = (width + 7) // 8           # bytes in row
        
        bitmap = bytearray(row_bytes * height)
        bitmap_ptr = ptr8(bitmap)
        
        image_data = f.read(height * block_size)
        image_ptr = ptr8(image_data)
        
        for row in range(height):
            # Y inversion, for bmp have up side down order 
            src_row = (height - 1 - row)
            dest_offset = row * row_bytes
            src_offset = src_row * block_size
            
            for b in range(row_bytes):
                #val = image_ptr[src_offset + b]
                bitmap_ptr[dest_offset + b] = image_ptr[src_offset + b] ^0xFF
        
        # Creation of temp FB and copy to main FB
        self.draw_bitmap( (bitmap, height, width), x, y, color )
        #fb = FrameBuffer(bitmap, width, height, MONO_HLSB)
        #self.blit(fb, x, y)

    def load_bmp( self, filename, x = 0, y = 0 ):
        """ Load 16-color BMP image on buffer
        Args
        filename (string): filename of image, example: "rain.bmp"
        x (int) : Start X position
        y (int) : Start Y position
        """
        f = open(filename, 'rb')

        if f.read(2) == b'BM':  #header
            dummy    = f.read(8)
            offset   = int.from_bytes(f.read(4), 'little')
            dummy    = f.read(4) #hdrsize
            width    = int.from_bytes(f.read(4), 'little')
            height   = int.from_bytes(f.read(4), 'little')
            planes   = int.from_bytes(f.read(2), 'little')
            depth    = int.from_bytes(f.read(2), 'little')
            compress = int.from_bytes(f.read(4), 'little')
            #print(offset, width, height, planes, depth, compress)
            
            if planes == 1 and depth == 4 and compress == 0: #compress method == uncompressed
                f.seek(offset)
                
                self.send_bmp_to_buffer( f, x, y, width, height)
                
        f.close()
        
    @micropython.viper
    def send_bmp_to_buffer( self, f, x:int, y:int, width:int, height:int):
        """ Send bmp-file to buffer
        Args
        f (object File) : Image file
        x (int) : Start X position
        y (int) : Start Y position        
        width (int): Width of image frame
        height (int): Height of image frame               
        """        
        row_size = ((width + 1) // 2 + 3) & ~3 # Aligning rows to 4 bytes
        
        total_size = height * row_size
        
        image_data = f.read(total_size)
        image_buffer = ptr8(image_data)
        
        bitmap = bytearray(total_size)
        bitmap_buffer = ptr8(bitmap)
        
        for h in range(height):
            offset = row_size * h
            for w in range(row_size):
                w_offset = offset + w
                image_byte = image_buffer[w_offset]
                bitmap_buffer[ total_size - 1 - w_offset ] = ((image_byte & 0x0F) << 4) | (image_byte >> 4)
                
        fb = FrameBuffer(bitmap, width, height, GS4_HMSB)
        self.blit(fb, x, y)
                        
